IF EXISTS (SELECT * FROM sys.databases WHERE name = 'BD_AlterDB1')
    BEGIN
    DROP DATABASE BD_AlterDB1;
    END 
CREATE DATABASE BD_AlterDB1

ALTER DATABASE BD_AlterDB1
ADD FILE (
	NAME='BD_AlterDB1_Data',
	FILENAME='C:\BD_AlterDB1\BD_AlterDB1_Data.ndf',
	SIZE = 3MB,
	FILEGROWTH= 2MB
)

ALTER DATABASE BD_AlterDB1
MODIFY FILE
(
	NAME = 'BD_AlterDB1_Data',
	SIZE= 5MB
)

ALTER DATABASE BD_AlterDB1
MODIFY FILE
(
	NAME = 'BD_AlterDB1_Data',
	SIZE= 3MB
)