IF EXISTS (SELECT * FROM sys.databases WHERE name = 'INSTITUTO')
    BEGIN
    DROP DATABASE INSTITUTO;
    END 

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name =
'INSTITUTO')
    BEGIN
    CREATE DATABASE INSTITUTO;
    END