CREATE DATABASE BDCreateDB2
ON PRIMARY (
NAME = BDCreateDB2_Data,
FILENAME = 'C:\BDCreateDB2\BDCreateDB2_Data.mdf',
SIZE = 3MB,
FILEGROWTH = 15%,
MAXSIZE = UNLIMITED)
LOG ON (
NAME = BDCreateDB2_Log,
FILENAME = 'C:\BDCreateDB2\BDCreateDB2_Log.ldf',
SIZE = 2MB,
FILEGROWTH = 15%,
MAXSIZE = 5MB
);